- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install docker -y

  - name : Start Docker Service
    command : sudo service docker start

  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 0834/banking-project-demo:3.0
